# Generated by Django 5.0.2 on 2024-03-04 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0006_likedcomment_comment_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedcomment',
            old_name='post',
            new_name='comment',
        ),
    ]
